corpool-frontend:
  replicaCount: 1

  image:
    repository: bogdan9926/corpool-frontend
    pullPolicy: IfNotPresent
    tag: "latest"

  service:
    type: ClusterIP
    port: 8080

  ingress:
    className: nginx
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/"
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    

  autoscaling:
    enabled: false

  serviceAccount:
    create: false

corpool-backend:
  replicaCount: 1

  image:
    repository: bogdan9926/corpool-backend
    pullPolicy: IfNotPresent
    tag: "latest"

  service:
    type: ClusterIP
    port: 33081

  ingress:
    enabled: false

  autoscaling:
    enabled: false

  serviceAccount:
    create: false

corpool-worker:
  replicaCount: 1

  image:
    repository: bogdan9926/corpool-worker
    pullPolicy: IfNotPresent
    tag: "latest"
  
  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false

  autoscaling:
    enabled: false

  serviceAccount:
    create: false
